# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Destino'),
        ),
    ]
